version: '3.9'

services:

  react-crud-web-api:
    container_name: react-crud-web-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8082:8081
    environment:
      - CHOKIDAR_USEPOLLING=true 